import type { Metadata } from 'next';
import Link from 'next/link';
import { JobTable } from '@/components/JobTable';
import { SearchBar } from '@/components/SearchBar';
import { AdSlot } from '@/components/AdSlot';
import { searchListings } from '@/lib/db';

/**
 * Results are rendered per request and never indexed.
 *
 * A search page is generated by whatever anyone types, which is the definition
 * of the thin programmatic surface D5 exists to keep out of the index. It is
 * for the visitor already here, not for Google.
 */
export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
	title: 'Search openings — PehlaJob',
	robots: 'noindex, follow',
};

export default async function SearchPage({
	searchParams,
}: {
	searchParams: Promise<{ q?: string }>;
}) {
	const { q = '' } = await searchParams;
	const query = q.trim();
	const results = query ? await searchListings(query) : [];

	return (
		<>
			<div className="head">
				<div className="wrap">
					<h1 className="head__title">
						{query ? `${results.length} matched “${query}”` : 'Search openings'}
					</h1>
					<p className="head__meta">
						<span>Company, role, city, skill or batch year</span>
					</p>
				</div>
			</div>

			<div className="wrap shell shell--solo">
				<div className="shell__main">
					<SearchBar q={query} />

					{query && results.length === 0 && (
						<p className="empty">
							Nothing matched. Try a company name, a city, or a single skill —{' '}
							<Link href="/">or browse everything open</Link>.
						</p>
					)}

					{results.length > 0 && <JobTable listings={results} />}

					{!query && (
						<p className="block__note block__note--lead">
							Type anything above. <Link href="/">Browse all openings</Link> if you would
							rather look around.
						</p>
					)}

					<AdSlot placement="foot" />
				</div>
			</div>
		</>
	);
}
